/**
 * `pnpm ports:pull` — write the seaports the site can quote to
 * src/data/ports.ts, from UN/LOCODE, with the fetch date on the file.
 *
 * The same parser the API's ingest uses, so the browser's list and the
 * service's table are the same rows from the same source. Only ports that
 * carry coordinates are kept: a port the list cannot place cannot be
 * priced by distance, and saying so is better than guessing where it is.
 */
import { writeFileSync } from "node:fs";
import { fetchUnlocodePorts, UNLOCODE_URL } from "../api/src/ingest/sources.ts";

const fetched = await fetchUnlocodePorts();
const placed = fetched
  .filter((p) => p.lat !== null && p.lon !== null)
  .sort((a, b) => a.unlocode.localeCompare(b.unlocode));

const rows = placed
  .map(
    (p) =>
      `  ["${p.unlocode}", ${JSON.stringify(p.name)}, ${p.lat!.toFixed(4)}, ${p.lon!.toFixed(4)}],`,
  )
  .join("\n");

const out = `// Generated by scripts/pull-ports.mts — do not edit by hand.
// Source: UN/LOCODE, ${UNLOCODE_URL}
// Fetched: ${new Date().toISOString()}
// Seaports in the routed countries: ${fetched.length}; with coordinates: ${placed.length}.

export const PORTS_META = {
  source: "unlocode",
  url: ${JSON.stringify(UNLOCODE_URL)},
  fetchedAt: ${JSON.stringify(new Date().toISOString())},
  seaports: ${fetched.length},
  withCoordinates: ${placed.length},
} as const;

/** [UN/LOCODE, name, latitude, longitude] */
export const PORT_ROWS: readonly (readonly [string, string, number, number])[] = [
${rows}
];
`;
writeFileSync(new URL("../src/data/ports.ts", import.meta.url), out);
console.log(`${placed.length} of ${fetched.length} seaports carry coordinates → src/data/ports.ts`);
